a = float(input())
b = float(input())
c = float(input())

# WRITE CODE BELOW THAT CHECKS HOW MANY ROOTS THE FUNCTION 
# f(x) = ax**2 + bx + c HAS AND OUTPUTS THESE. 
# ROUND THE ROOTS TO ONE DECIMAL PLACE, USING THE round FUNCTION 
# THAT IS BUILT INTO PYTHON. YOU CAN USE YOUR IDE TO EXPLAIN 
# THE round FUNCTION.